[project]
name = "hello-world"
dynamic = ["version"]

[tool.setuptools.dynamic]
version = { attr = "hello_world.__version__" }

[project.scripts]
hello-world = "hello_world:main" # which means `from hello_world import main; main()`
